version: '3.9'

services:
  db:
    build:
      context: ./db
    container_name: sqlite-db
    volumes:
      - ./db/ecommerce.db:/app/instance/ecommerce.db
    networks:
      - app-network

  customer_service:
    build:
      context: ./customer_service
    container_name: customer_service
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./customer_service:/app
    networks:
      - app-network

  inventory_service:
    build:
      context: ./inventory_service
    container_name: inventory_service
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./inventory_service:/app
    networks:
      - app-network

  sales_service:
    build:
      context: ./sales_service
    container_name: sales_service
    depends_on:
      - db
    ports:
      - "6000:6000"
    volumes:
      - ./sales_service:/app
    networks:
      - app-network

  reviews_service:
    build:
      context: ./reviews_service
    container_name: reviews_service
    depends_on:
      - db
    ports:
      - "7000:7000"
    volumes:
      - ./reviews_service:/app
    networks:
      - app-network

networks:
  app-network:
